package Aplication;

import NutriSoft.model.CalculoGastoCalorico;
import javax.swing.JOptionPane;


/**
 *
 * @author patri
 */
public class GastoCaloricoAplication extends javax.swing.JFrame {

    /**
     * Creates new form CalculoGastoCalorico
     */
    public GastoCaloricoAplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Voltar1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        ButtonHomen = new javax.swing.JRadioButton();
        ButtonMulher = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        Peso = new javax.swing.JTextField();
        Altura = new javax.swing.JTextField();
        Idade = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        GastoTotal = new javax.swing.JLabel();
        GastoBasal = new javax.swing.JLabel();
        TextPeso = new javax.swing.JLabel();
        TextAltura = new javax.swing.JLabel();
        TextIdade = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Voltar1.setText("< Voltar");
        Voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Calculo de Gasto Calórico");

        ButtonHomen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonHomen.setText("Homen");
        ButtonHomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHomenActionPerformed(evt);
            }
        });

        ButtonMulher.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonMulher.setText("Mulher");
        ButtonMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMulherActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nivel Atividade :");

        Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoActionPerformed(evt);
            }
        });

        Altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlturaActionPerformed(evt);
            }
        });

        GastoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GastoTotal.setText(" Gasto Total :");
        GastoTotal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                GastoTotalComponentAdded(evt);
            }
        });

        GastoBasal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GastoBasal.setText("Gasto Basal :");
        GastoBasal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                GastoBasalComponentAdded(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GastoTotal)
                    .addComponent(GastoBasal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(GastoBasal)
                .addGap(28, 28, 28)
                .addComponent(GastoTotal)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        TextPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPeso.setText("Peso (kg) :");

        TextAltura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextAltura.setText("Altura(cm) :");

        TextIdade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextIdade.setText("Idade :");

        Calcular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Calcular.setText("Calcular");
        Calcular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentário", "Leve (exercício leve 1 a 3 dias/semana)", "Moderado (exercício moderado 3 a 5 dias/semana)", "Ativo (exercício pesado 5 a 6 dias/semana)", "Extremamente ativo (exercício pesado diário)", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Voltar1)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextIdade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Idade, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonHomen)
                                .addGap(100, 100, 100)
                                .addComponent(ButtonMulher))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(Calcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonHomen)
                            .addComponent(ButtonMulher))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextPeso)
                        .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextAltura))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextIdade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Voltar1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  


    private void Voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar1ActionPerformed
        dispose();
    }//GEN-LAST:event_Voltar1ActionPerformed

    private void ButtonHomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHomenActionPerformed
   
    }//GEN-LAST:event_ButtonHomenActionPerformed

    private void AlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlturaActionPerformed

    private void PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesoActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
   
    String pesoText = Peso.getText();
    String alturaText = Altura.getText();
    String idadeText = Idade.getText();
    
    
    if (pesoText.isEmpty() || alturaText.isEmpty() || idadeText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        double peso = Double.parseDouble(pesoText);
        double altura = Double.parseDouble(alturaText);
        double idade = Double.parseDouble(idadeText);

        CalculoGastoCalorico calculadora;

        if (ButtonHomen.isSelected()) {
            calculadora = new CalculoGastoCalorico(peso, altura, idade, "Homem");
        } else if (ButtonMulher.isSelected()) {
            calculadora = new CalculoGastoCalorico(peso, altura, idade, "Mulher");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione o sexo.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double calBasal = calculadora.getCalculo();

        double calTotal;

        switch (jComboBox1.getSelectedIndex()) {
            case 0:
                calTotal = calBasal * 1.2;
                break;   // Sedentário
            case 1:
                calTotal = calBasal * 1.375;
                break; // Leve
            case 2:
                calTotal = calBasal * 1.55;
                break;  // Moderado
            case 3:
                calTotal = calBasal * 1.725;
                break; // Ativo
            case 4:
                calTotal = calBasal * 1.9;
                break;   // Extremamente ativo
            default:
                JOptionPane.showMessageDialog(this, "Selecione o nível de atividade.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
        } 
        GastoBasal.setText(String.format("Gasto Basal: %.2f", calBasal));
        GastoTotal.setText(String.format("Gasto Total: %.2f", calTotal));
    } catch (NumberFormatException e) {
      
        JOptionPane.showMessageDialog(this, "Insira valores numéricos válidos.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_CalcularActionPerformed

    private void GastoTotalComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_GastoTotalComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_GastoTotalComponentAdded

    private void GastoBasalComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_GastoBasalComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_GastoBasalComponentAdded

    private void ButtonMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMulherActionPerformed
     
    }//GEN-LAST:event_ButtonMulherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GastoCaloricoAplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Altura;
    private javax.swing.JRadioButton ButtonHomen;
    private javax.swing.JRadioButton ButtonMulher;
    private javax.swing.JButton Calcular;
    private javax.swing.JLabel GastoBasal;
    private javax.swing.JLabel GastoTotal;
    private javax.swing.JTextField Idade;
    private javax.swing.JTextField Peso;
    private javax.swing.JLabel TextAltura;
    private javax.swing.JLabel TextIdade;
    private javax.swing.JLabel TextPeso;
    private javax.swing.JToggleButton Voltar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

   
}
