package Aplication;

/**
 *
 * @author patri
 */
public class Nutrisoft extends javax.swing.JFrame {

    /**
     * Creates new form Nutrisoft
     */
    public Nutrisoft() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NutriSoft = new javax.swing.JPanel();
        Recomendacoes = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        GastoCalorico1 = new javax.swing.JButton();
        IMCbutton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Recomendacoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Recomendacoes.setText("RECOMENDAÇÕES");
        Recomendacoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Recomendacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecomendacoesActionPerformed(evt);
            }
        });

        Sair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Sair.setText("SAIR");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        GastoCalorico1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GastoCalorico1.setText("GASTO CALÓRICO");
        GastoCalorico1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GastoCalorico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GastoCalorico1ActionPerformed(evt);
            }
        });

        IMCbutton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        IMCbutton.setText("IMC");
        IMCbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IMCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMCbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NutriSoftLayout = new javax.swing.GroupLayout(NutriSoft);
        NutriSoft.setLayout(NutriSoftLayout);
        NutriSoftLayout.setHorizontalGroup(
            NutriSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NutriSoftLayout.createSequentialGroup()
                .addGroup(NutriSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NutriSoftLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NutriSoftLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(NutriSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IMCbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(NutriSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(GastoCalorico1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Recomendacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        NutriSoftLayout.setVerticalGroup(
            NutriSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NutriSoftLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(IMCbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(GastoCalorico1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Recomendacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NutriSoft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NutriSoft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecomendacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecomendacoesActionPerformed
       Recomendacoes telaRecomendacoes = new Recomendacoes();
       telaRecomendacoes.setVisible(true);
    }//GEN-LAST:event_RecomendacoesActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void GastoCalorico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GastoCalorico1ActionPerformed
       GastoCaloricoAplication gastoCaloricoApp = new GastoCaloricoAplication();
        gastoCaloricoApp.setVisible(true);
    }//GEN-LAST:event_GastoCalorico1ActionPerformed

    private void IMCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMCbuttonActionPerformed
       IMC imc = new IMC();
       imc.setVisible(true);
    }//GEN-LAST:event_IMCbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nutrisoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nutrisoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nutrisoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nutrisoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nutrisoft().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GastoCalorico1;
    private javax.swing.JToggleButton IMCbutton;
    private javax.swing.JPanel NutriSoft;
    private javax.swing.JButton Recomendacoes;
    private javax.swing.JButton Sair;
    // End of variables declaration//GEN-END:variables
}
